### ISSUE TITLE
is  cv::MAt NEW = cv::Mat X - Cv::Mat Y fast enough ?

### ISSUE THREAD

**Issue by MyraBaba** [njvisionpower/mxnet-cpp-insightface#10]
Hi,

I tested 800.000 faces with 512 features and 👍 

`        class_info result = classify(output, data );
`

takes almost 2 seconds in mac book pro 2.4 Ghz 16 gig ram.

Do you think its fast enough ?

Or is it faster using the std::vector for subtract , power and loop for below threshold values ? 

which one ?

**Comment by njvisionpower** [comment]
In feature inference phase, the most time spent should be forward of ResNet or other similar deep network(if you use 512 feature) instead of matrix operation(for (800, 512) dim). So what's your test detail, did you mean extract one face feature and compare with 800 faces and take 2 seconds? One face takes 2s I think is slow.

**Comment by MyraBaba** [comment]
yes there is 800.000 faces an theirs 512 descriptors.

I want to produce distance and similary of a new photo over those faces. 
it takes to much time.
